function [fitresult, gof] = gammaFit(x, lums)
    %CREATEFIT(X,LUMS)
    %  Create a fit.
    %
    %  Data for 'untitled fit 1' fit:
    %      X Input : x
    %      Y Output: lums
    %  Output:
    %      fitresult : a fit object representing the fit.
    %      gof : structure with goodness-of fit info.
    %
    %  See also FIT, CFIT, SFIT.

    %  Auto-generated by MATLAB on 30-Jan-2018 17:44:24

    [xData, yData] = prepareCurveData( x, lums );

    % Set up fittype and options.
    ft = fittype( 'a + (b + k*x)^gamma', 'independent', 'x', 'dependent', 'y' );
    opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
    opts.Display = 'Off';
    opts.Lower = [0 0 0 0]; % [a b gamma k]
    opts.Robust = 'Bisquare';
    opts.StartPoint = [min(x)/5 0.5 2 1];
    opts.Upper = [200 200 5 200];

    % Fit model to data.
    [fitresult, gof] = fit( xData, yData, ft, opts );

%     % Plot fit with data.
%     figure( 'Name', 'gamma fcn' );
%     h = plot( fitresult, xData, yData );
%     legend( h, 'lums vs. x', 'untitled fit 1', 'Location', 'NorthEast' );
%     % Label axes
%     xlabel x
%     ylabel lums
%     grid on
%
end


